### ISSUE TITLE
Add Ranks to statistics overview

### ISSUE THREAD

**Issue by howeverAT** [raphi011/scores-api#28]
101% Stupid Hacker
100%  Hacker
99% Administrator
90% Gigant Wall
85% 5 Star Tournament Player
80% Senior Beacher
78% Supreme Master First Class 
76% Legend
72% Veteran
70% Enhanced Partypupser
68% Volleyball pregnant
66% King of the Beach
64% Game-Farmer
62% Muscle Men
60% Ball Magnet
58% Monster Block
56% Guy with good Beach Life Balance
54% One Hand Defender
52% Waiting for the next poolparty
50% Ying and yang teacher
48% Knows all the players by their name
46% Veteran
44% Under Net Hitter 
42% Sand Worm
40% Inverted Cut
38% Timeout Caller
36% Sidecourt ball boy
34% Last at gürsel room party  
32% Foodblogger
30% party crew
20% third world beachvolleyballl player
10% Junior
5% Greenhorn
2% Newbie

**Comment by raphi011** [comment]
How long did it take you to compile this list? :P

**Comment by howeverAT** [comment]
odd values are still missing :D
