### ISSUE TITLE
Filter loses settings after change to different page 

### ISSUE THREAD

**Issue by howeverAT** [raphi011/scores-api#94]
Action: set your filter settings, change to Ladder, return to Tournaments again,
Result: Settings back to default 
Expected Result: Filter settings should be persistent

**Comment by raphi011** [comment]
already working on that .. it's kind of annoying i know :)

**Comment by raphi011** [comment]
The filter should work something like this:

Filter parameters are set by query arguments, e.g. : `/tournaments?gender=W`.

**IF** query arguments were passed -> use these filters to get the tournaments and remember them in the browser.
**IF NO** query arguments were passed, e.g.: if redirecting to `/tournaments` or `/` via a link automatically use the last query used.

@LukasWi sounds good?

**Comment by howeverAT** [comment]
you mean this is only temporary persistent for the actual browser session? hmm i would prefer a browser session independent way
